services:
  web:
    volumes:
      - ../../apps/web:/app
      - web-node-modules:/app/node_modules
    ports:
      - "127.0.0.1:4200:4200"

  api:
    environment:
      DATABASE_URL: "postgresql://convive:convive-development-only@database:5432/convive?serverVersion=18.4&charset=utf8"
      SESSION_DATABASE_URL: "pgsql:host=database;port=5432;dbname=convive;user=convive;password=convive-development-only"
    volumes:
      - ../../apps/api:/app
    ports:
      - "127.0.0.1:8000:8000"

  database:
    environment:
      POSTGRES_DB: convive
      POSTGRES_USER: convive
      POSTGRES_PASSWORD: convive-development-only
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  web-node-modules:

networks:
  frontend:
    internal: false
  backend:
    internal: false
